name: dl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - tmux
  - htop
  - transformers
  - pip
  - pip:
    - accelerate
    - bitsandbytes
